### ISSUE TITLE
Should we add `types.is_depset`?

### ISSUE THREAD

**Issue by allevato** [bazelbuild/bazel-skylib#104]
We're migrating rules_swift to use the `types` module instead of `type(foo) == type(bar)`, but we can't update all of them since there's not a `types.is_depset`. I have to check the type because I'm writing action wrappers that need to augment the tools/inputs passed into them, which means knowing whether it's a depset or a list and performing the right operation.

Any reason we shouldn't do this?

**Comment by laurentlb** [comment]
I think we can add it.
