### ISSUE TITLE
Should we add `types.is_struct`?

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/bazel-skylib#106]
Like in #104, we're migrating rules_apple, and we have some places where we use a `string` or skylib's `partial`, we currently deal with this mainly by checking if it is a struct, the one catch is we also support `None` for the string, so flipping it to `types.is_string` doesn't exactly match.  So, does it make sense to add `types.is_struct` to round out `types`?

**Comment by laurentlb** [comment]
Closing for now, but can be re-discussed if more people want it.

You can also define a short function in your file if needed.
