### ISSUE TITLE
Attach source archives and sha256 sums to releases

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-skylib#12]
Please attach source archives and sha256 sums to GitHub releases (both current and future releases) so they can be used safely with `http_archive`.

Source archives can be prepared like this:

```
$ git archive --output=bazel-skylib-0.2.0.tar.gz 0.2.0
$ sha256sum bazel-skylib-0.2.0.tar.gz 
61e358bd51312b5a31b8f81f9755b587bc240472b34054e2c2aff792b48eab10  bazel-skylib-0.2.0.tar.gz
```

GitHub has provides links to source archives on releases, but these are *not safe* for `http_archive`. They are generated on the fly and don't have stable sha256 sums. Earlier, [GitHub broke Bazel, Homebrew, and other systems](https://github.com/libgit2/libgit2/issues/4343) when they upgraded their internal software. 

Source archives that are manually generated and attached to releases won't change and are safe.

**Comment by aiuto** [comment]
@jayconrod Is the release format as of 0.9.0 acceptable?

**Comment by jayconrod** [comment]
That works. I'd advocate for semantic versions in general, but I think that's the plan of record in Bazel repos already.

FYI, in the last few months, I've been asked to save rules_go archives in the bazel-mirror GCS bucket. URLs look like `"https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/0.18.7/rules_go-0.18.7.tar.gz"`. I think this is a good practice, and I'd recommend this as well.

**Comment by aiuto** [comment]
Yes. That is the plan. 0.8.0 -> 0.9.0 would follow because we (I think) only added features.

FWIW. I am trying to come up with a packaging toolkit so that rule owners can more easily make distributions that follow common idioms.
