### ISSUE TITLE
Incompatible changes to maprule

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel-skylib#126]
Context: https://groups.google.com/d/msg/bazel-discuss/jp9RLsiVhD8/3M0wdWFoCgAJ

/cc @laurentlb 

Plans:
- `add_env` and `outs_templates` attributes: update requirements for dict keys. The rule would no longer prefix these with `MAPRULE_`. Instead the the name would have to start with `MR_`.

  **Rationale**: more obvious connection with their use in the `cmd` attribute, and `MR_` is easier to type than `MAPRULE_`.
- Envvars of the action: they would start with `MR_` instead of `MAPRULE_`.

  **Rationale**: easier to type.

Questions:
1. May I proceed with these incompatible changes?
2. When is the next release due? I hope to merge my changes beforehand.

**Comment by laszlocsomor** [comment]
ping

**Comment by c-parsons** [comment]
1. Seems fine to me -- we have to consistently weigh migration pain / confusion vs. overall goodness of the change. I don't have a good sense for current maprule usage :) I defer to you on this, since you authored maprule. We don't have a strict policy here.
2. We don't have a strict release schedule -- it's manual. I mostly cut on request, or if and when we have a new feature we want to push.

**Comment by laszlocsomor** [comment]
Thank you!

1. I have no data on maprule adoption. It's not in any Skylib release yet, so I'm assuming no/little adoption. Skylib is experimental, breaking changes are OK.
2. Great!

**Comment by laszlocsomor** [comment]
> Skylib is experimental

I meant this:

>> This library is currently under early development. Be aware that the APIs in these modules may change during this time.

(https://github.com/bazelbuild/bazel-skylib/blob/2d1669ed882652e5fc695bb99c77442a9273ff56/README.md)

**Comment by laurentlb** [comment]
I agree we can make changes to maprule (better now than later).

But we shouldn't treat Skylib as experimental: almost everything depends on it. In general, we should be careful with breaking changes (especially when it's in a release).

**Comment by laszlocsomor** [comment]
Acknowledged.

Another planned incompatible change to maprule: merge `cmd_maprule` and `bash_maprule`, introduce a `language` attribute. **Rationale**: allows `select()`ing on platform, so `bazel build //foo:all` works.

**Comment by tetromino** [comment]
No longer relevant - maprule removed in #192.
