### ISSUE TITLE
Windows: implement native_binary and native_test rules

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel-skylib#148]
Implement rules that allow wrapping a native binary (or native script) in a `_binary` and `_test` rule, so we can `bazel run` and `bazel test` it, or use as `tools` entry for other rules.

Desired semantics:
```
native_test(
  name = "my_bin",
  src = "my_bin.exe",
  args = ["--data=$(location some-data.txt)"],
  data = ["some-data.txt"],
)
```

Crucially these rules should use `ctx.actions.run` and NOT `ctx.actions.run_shell`, to avoid depending on Bash.

**Comment by laurentlb** [comment]
Do you plan to work on this?

IMO, that would be great to have this (and #149) before publishing the blog post about living in a bash-less world.

**Comment by laszlocsomor** [comment]
Yes, and yes I agree.

**Comment by laszlocsomor** [comment]
Wow, living in the future! ![image](https://user-images.githubusercontent.com/10532244/57382799-dfd3ee80-71ad-11e9-986e-b754c1d8eff0.png)

**Comment by erenon** [comment]
The documentation referencing these rules link to non-existent pages:
https://docs.bazel.build/versions/master/skylark/windows_tips.html

run_binary() (source, **documentation**): runs a binary (or *_binary rule) with given inputs and expected outputs as a build action (this is a build rule wrapper for ctx.actions.run)

native_binary() (source, **documentation**): wraps a native binary in a *_binary rule, which you can bazel run or use in run_binary()’s tool attribute or 

The bold links are dead.
