### ISSUE TITLE
Update WORKSPACE setup instructions on new releases

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel-skylib#174]
0.9.0 is  [released](https://github.com/bazelbuild/bazel-skylib/releases/tag/0.9.0) but the main page's [WORKSPACE setup notes](https://github.com/bazelbuild/bazel-skylib#workspace-file) still use 0.8.0.

Maybe already covered by https://github.com/bazelbuild/bazel-skylib/issues/109, but this seems important enough to specifically highlight.

**Comment by aiuto** [comment]
We start on this path with #185 .  That will generate a workspace stanza with the correct URL and sha256. Then we can make the main page refer you to the release.

**Comment by tetromino** [comment]
Afaict, this has been fixed: https://github.com/bazelbuild/bazel-skylib#workspace-file points to https://github.com/bazelbuild/bazel-skylib/releases which lists the correct urls/tarballs for any given release.
