### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel-skylib#193]
We would like to have a 1.0.0 release to include as the baseline in bazel-federation.
Right now we are in the sad position of having to point at a commit rather than a release.

@aiuto is prepared to do this by October 1, unless anyone else wants to step up.

CC: @fweikert

**Comment by thomasvl** [comment]
You might want to ensure a pass is made thru PRs before the cut, last time I looked, I thought there were even PRs that got approved that haven't been landed for some reason.

**Comment by aiuto** [comment]
I do not understand why people don't land PRs.
IMO anything older than the last release (0.9.0 on July 12) is too stale to consider merge without re-review.

That leaves
- 3 things dealing with --incompatible_remap_main_repo - which is its own mess
- one about sets.  Which is supposed to be an enhancement, so it could go in 1.1.0.
- #194  is a WIP
- and #190 is the only one to consider.  Which I just merged.

**Comment by aiuto** [comment]
1.0.0 was defective. Missing unittest tooling
1.0.1 is now out.
