### ISSUE TITLE
1.0 release has different directions from rest of dep

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/bazel-skylib#198]
https://github.com/bazelbuild/bazel-skylib/releases/tag/1.0.0

> ```
> load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
> http_archive(
>     name = "bazel-skylib",
>     url = "https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.0/bazel-skylib-1.0.0.tar.gz",
>     sha256 = "e72747100a8b6002992cc0bf678f6279e71a3fd4a88cab3371ace6c73432be30",
> )
> load("@bazel-skylib//:deps.bzl", "bazel-skylib_dependencies")
> bazel-skylib_dependencies()
> ```

But the `WORKSPACE` and all the docs say to call it `bazel_skylib`.

The last load also tries to load `deps.bzl` which does not exist, `workspace.bzl` does.  `bazel-skylib_dependencies` isn't a valid Starlark symbol either.

**Comment by aiuto** [comment]
Yup. Oversight on my part. I did a quick fix of editing the site.
I'll send a PR to update the packaging so that does not happen again.

**Comment by aiuto** [comment]
This is fixed now - but I have downgraded the release to pre-release until 1.0.1 can come out to fix #199
