### ISSUE TITLE
rules/empty_test.sh isn't executable in tar.gz

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/bazel-skylib#204]
`rules/build_test.bzl` uses `empty_test.sh`, but in the download it is no longer executable, so it builds trying to use it fail.

```
$ wget -O - https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.0/bazel-skylib-1.0.0.tar.gz 2>/dev/null | tar tvzf - | grep empty
-r--r--r-- 0/0             103 1999-12-31 19:00 ./rules/empty_test.sh
```

**Comment by thomasvl** [comment]
https://buildkite.com/bazel/rules-apple-darwin/builds/1834#b38afdc8-646d-4adf-91e7-7f585aa593df show some of the failures when trying to use it.

**Comment by aiuto** [comment]
I believe 1.0.2 fixes this.
