### ISSUE TITLE
Typo in Workspace Setup in Release Notes of 1.0.1

### ISSUE THREAD

**Issue by t-soliduslink** [bazelbuild/bazel-skylib#205]
Currently (2019-10-09 12:45 UTC), it is saying:

```
http_archive(
    name = "bazel-skylib",
```

whereas the name should be `bazel_skylib` (underscore rather than dash)

**Comment by aiuto** [comment]
Damm.. Yes. I can adjust the notes.

**Comment by aiuto** [comment]
Done.
FWIW, the tools we use to produce the sample release notes have the fix to convert - to _, but we still have to update bazel-skylib to use those new rules, so this problem should be dimishing.
