### ISSUE TITLE
diff_test() could accept a message to print on failure

### ISSUE THREAD

**Issue by malcolmr** [bazelbuild/bazel-skylib#216]
I've been looking at replacing a home-grown implementation of `diff_test()` with the version here, and one feature that's missing is the ability to provide a message to output on failure.

In particular, this is useful for golden tests, where the expected output can be regenerated with a command. (It's also useful for checked-in generated files, for the same reason.)

e.g. I'd like to be able to write something like

```bzl
diff_test(..., failure_message = "Please run ... to update expected output.")
```

(The only complication here might be quoting, if the message argument contains quotes. The home-grown version I'm using sidesteps that by asserting that there are no single-quotes in the failure_message.)

**Comment by Kernald** [comment]
Expanding on that, having a way to copy `file2` to the location of `file1` (or vice-versa, although we'd need to assume one is the reference, which doesn't sound that weird in this context) built into that rule would be quite nice - and would potentially remove the need for a customised failure message altogether?

**Comment by caseyduquettesc** [comment]
Seems like this was addressed by https://github.com/bazelbuild/bazel-skylib/pull/307?

**Comment by malcolmr** [comment]
Looks like it, thanks! I don't know if it's worth filing a separate issue for the copying mentioned above, but otherwise feel free to close this one.

**Comment by tetromino** [comment]
Closing as fixed :)
