### ISSUE TITLE
Need a new release

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel-skylib#246]
Since the last release, there have been a few fixes (in particular for --incompatible_disable_depset_items) for compatibility with Bazel 4.0.

We should do a new release.

**Comment by laurentlb** [comment]
cc @aiuto

**Comment by aiuto** [comment]
It should probably be 2.0.0 since old_sets.bzl was removed.

**Comment by aiuto** [comment]
Well. It seems like I forgot my own advice and released 1.0.3 with old_sets removed. Like i said there, if this is a problem, we can rebrand as 2.0.0 if this actually causes problems.
There don't seem to be any rules under bazelbuild still using old_sets.
https://github.com/search?q=org%3Abazelbuild+old_sets&type=Code,
