### ISSUE TITLE
Release 1.0.3 of bazel-skylib

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel-skylib#269]
Currently bazel-federation is using 1.0.2 bazel-skylib, where tests:inspect_output_dirs_test fails (problem in the test), after bazel commit bazelbuild/bazel@a7a0d48.

This has been fixed in bazel-skylib commit 68acaa, https://github.com/bazelbuild/bazel-skylib/pull/267.

However to fix bazel-federation testing a new release of bazel-skylib is necessary.

**Comment by aiuto** [comment]
We should do a skylib release. I can do that Tuesday if no one does today.

**Comment by comius** [comment]
That would be awesome!

**Comment by aiuto** [comment]
https://github.com/bazelbuild/bazel-skylib/pull/270  update the version
stamp and CHANGELOG
The only changes which might break people are removals of long deprecated
items. If this turns out to be a problem we could revoke the release and
rename to 2.0.0.

**Comment by aiuto** [comment]
Done
