### ISSUE TITLE
Add a library for binary prefixes (Ki/Mi/Gi/etc.)

### ISSUE THREAD

**Issue by cvrebert** [bazelbuild/bazel-skylib#282]
As of https://github.com/bazelbuild/bazel/commit/3ed7ed57e2ba144933da37c19c7d93b89d39a90e , Bazel now supports large integers. Yay!
It's useful in some cases to specify digital storage sizes in definitions of Bazel targets. For example, "this test target is limited to using X GiB of disk space and Y MiB of RAM". It was previously only possible to specify this using strings; e.g. `foo_test(ram = "500K", disk = "2G")`. This new Bazel feature allows such values to be expressed as proper integers, which thus allows syntax errors to be detected much earlier and for arithmetic on such values to be performed at the Starlark layer. 

However, specifying larger values in a readable fashion remains annoying. Bazel doesn't support the exponentiation operator (`**`), so `ram = 2**30` isn't possible. One could write `ram = 1 << 30`, but many engineers don't use bit-shifts in their day-to-day coding involving "higher-level" languages. Both cases would require memorizing `Gi = 2**30`, etc.

Thus, I propose adding a library (for the sake of argument, `units.bzl`) containing functions or constants so such values can be written more readably; e.g.

```py
load(":units.bzl", "units", "KIBI", "GIBI")

foo_test(
    # ...
    ram = 500 * KIBI,
    disk = 2* GIBI,
)

foo_test(
    # ...
    ram = units.Ki(4),
    disk = units.Gi(4),
)
```

This would be analogous to existing libraries in other languages which are used when writing Borg job configurations.

**Comment by alandonovan** [comment]
Please define this library in your own project for the time being. If there appears to be a recurring need for a stable set of features, we could consider adding something to skylib.

**Comment by tetromino** [comment]
>  Bazel doesn't support the exponentiation operator (`**`), so `ram = 2**30` isn't possible.

But we could fix that! I've now proposed https://github.com/bazelbuild/starlark/issues/190

I would agree that Alan that it's not clear that there's a recurring need for a units library beyond having a power operator.
