### ISSUE TITLE
Feature request: Windows support in paths

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/bazel-skylib#283]
I noticed `paths` only supports POSIX paths. Would it be possible to have support for windows paths as well?

**Comment by UebelAndre** [comment]
Friendly ping here

**Comment by alandonovan** [comment]
All of the paths that are inputs to Bazel (from command lines, BUILD files, glob, and so on) are slash-separated, and all of the paths presented to Bazel's Starlark API are slash-separated. The two places where conversion to Windows-style paths should be necessary are (a) the underlying system calls made by Bazel itself (and Windows mostly accepts slash-separated paths) and (b) paths written in files or passed as arguments to applications that do not treat them as opaque filenames. In the latter case, you should backslashify the paths when preparing to emit the output for that application. Think of it as converting from a Bazel path to an application-specific string. It doesn't seem to me that it should be skylib's responsibility.

**Comment by UebelAndre** [comment]
So whenever interacting with `bazel_skylib`, is the suggestion that users have sanitized their paths to all use forward slashes?

**Comment by alandonovan** [comment]
That's the assumption throughout the entire build language.

**Comment by UebelAndre** [comment]
Ah cool! Then that works for me. Thanks for taking the time to explain that 🙏
