### ISSUE TITLE
diff_test fails on windows with --enable_runfiles

### ISSUE THREAD

**Issue by erenon** [bazelbuild/bazel-skylib#313]
To reproduce, on windows:

    > bazel test tests/diff_test/...  --enable_runfiles

Root cause:

```
set MF=%RUNFILES_MANIFEST_FILE:/=\\%
set PATH=%SYSTEMROOT%\\system32
set F1={file1}
set F2={file2}
if "!F1:~0,9!" equ "external/" (set F1=!F1:~9!) else (set F1=!TEST_WORKSPACE!/!F1!)
if "!F2:~0,9!" equ "external/" (set F2=!F2:~9!) else (set F2=!TEST_WORKSPACE!/!F2!)
for /F "tokens=2* usebackq" %%i in (`findstr.exe /l /c:"!F1! " "%MF%"`) do (
  set RF1=%%i
  set RF1=!RF1:/=\\!
)
```

https://github.com/bazelbuild/bazel-skylib/blob/main/rules/diff_test.bzl#L36

The batch script expects that a MANIFEST file exists, but it does not, if `--enable_runfiles` is set, even if `--build_runfiles_manifests` is also set.

**Comment by erenon** [comment]
Possible solution: if `RUNFILES_DIR` envvar is set, search for the files there, otherwise use the manifest file.

**Comment by tetromino** [comment]
I've asked Bazel's Windows expert (@meteorcloudy) for a review of #314.
