### ISSUE TITLE
Request for Release

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/bazel-skylib#316]
Would it be possible to get a new release of `bazel_skylib`?

**Comment by tetromino** [comment]
Sure, it would be possible. Is there a specific change you are waiting for, out of curiosity?

**Comment by UebelAndre** [comment]
> Sure, it would be possible. Is there a specific change you are waiting for, out of curiosity?

Yes: https://github.com/bazelbuild/bazel-skylib/pull/299

**Comment by tetromino** [comment]
Done: https://github.com/bazelbuild/bazel-skylib/releases/tag/1.1.1 (initial 1.1.0 tag missed the update for version.bzl)
