### ISSUE TITLE
release process doesn't include mirroring

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-skylib#332]
If users follow the documented install snippet for WORKSPACE, they get

```
 WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/archive/1.1.1.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
```

I suspect this is a systemic problem with the process, not a one-time thing for the latest version.

**Comment by tetromino** [comment]
Please read the [documented snippet](https://github.com/bazelbuild/bazel-skylib/releases/tag/1.1.1) more carefully: it's https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.1.1/bazel-skylib-1.1.1.tar.gz

Not archive/1.1.1.tar.gz

Still, it's worth adding a maintainer's guide to document the exact commands for mirroring the artifact.

**Comment by alexeagle** [comment]
Oops! Sorry for the noise, 🙏🏻
