### ISSUE TITLE
Could a new release be made to accommodate the portable shebang line?

### ISSUE THREAD

**Issue by yesudeep** [bazelbuild/bazel-skylib#336]
I'm referring to:

* Issue: https://github.com/bazelbuild/bazel-skylib/issues/328
* PR: https://github.com/bazelbuild/bazel-skylib/pull/329

Will be useful for dependents:
* https://github.com/bazelbuild/rules_foreign_cc/pull/794/commits/bc3d061643ccb2eb5442a761e292e6e7b0b6bb8c

**Comment by jsharpe** [comment]
@tetromino could this be done please so that I can take a first shot at implementing bzlmod for rules_foreign_cc?

**Comment by UebelAndre** [comment]
@tetromino friendly ping 😅

**Comment by tetromino** [comment]
Sorry for the delay! Will be fixed by https://github.com/bazelbuild/bazel-skylib/pull/350

**Comment by tetromino** [comment]
Released https://github.com/bazelbuild/bazel-skylib/releases/tag/1.2.0
