### ISSUE TITLE
subpackages module referenced in Bazel docs missing

### ISSUE THREAD

**Issue by happenslol** [bazelbuild/bazel-skylib#345]
The Bazel docs for the native module reference this library [here](https://docs.bazel.build/versions/main/skylark/lib/native.html#subpackages) with the following sentences:

> Returns a new mutable list of every direct subpackage of the current package, regardless of file-system directory depth. List returned is sorted and contains the names of subpackages relative to the current package. **It is advised to prefer using the methods in bazel_skylib.subpackages module rather than calling this function directly.**

However, there is no subpackages module, and I looked a few versions back and can't find one either. Am I missing something or has the module been removed at some point?

**Comment by aiuto** [comment]
subpackages is only a few days old.  The documentation from the function at head is probably ahead of the rest of the scaffolding needed to use it.

cc: @kkress

**Comment by kkress** [comment]
Yup subpackages() was added on Tuesday (3 days ago) and shouldn't yet be in any released bazel.   I'm waiting on some internal reviews from bazel_skylib folks before sending the PRs to the bazel_skylib repo.

@brandjon @allevato @c-parsons

**Comment by happenslol** [comment]
Interesting, that clears it up then. Thanks for the quick response!
