### ISSUE TITLE
`unittest` with `partial.make` only seems to work for `timeout` parameter name.

### ISSUE THREAD

**Issue by tillahoffmann** [bazelbuild/bazel-skylib#371]
I've been trying to use `make.partial` in for running `unittest`s. Copying the `basic_passing_short_timeout_test` test from `bazel-skylib/tests/unittest_tests.bzl` works as expected. However, if I add another test with `timeout` consistently renamed to `fallout`, the tests fail with the following error message.

```
ERROR: /path/to/BUILD: //partial_test:partial_tests_test_1: no such attribute 'fallout' in 'basic_passing_short_fallout_test' rule
```

Do I need to register the attribute name somewhere to be able to use it with `partila.make`? I'm using the 1.2.1 release.

The full `partial_test.bzl` file is copied below.

```python
load("@bazel_skylib//lib:unittest.bzl", "asserts", "unittest")
load("@bazel_skylib//lib:partial.bzl", "partial")


# Test copied from the skylib test suite.
def _basic_passing_short_timeout_test(ctx):
    env = unittest.begin(ctx)
    asserts.equals(env, ctx.attr.timeout, "short")
    return unittest.end(env)

basic_passing_short_timeout_test = unittest.make(_basic_passing_short_timeout_test)


# Same test but renamed timeout -> fallout.
def _basic_passing_short_fallout_test(ctx):
    env = unittest.begin(ctx)
    asserts.equals(env, ctx.attr.fallout, "short")
    return unittest.end(env)

basic_passing_short_fallout_test = unittest.make(_basic_passing_short_fallout_test)


def partial_test_suite(name):
    unittest.suite(
        name,
        partial.make(basic_passing_short_timeout_test, timeout = "short"),
        # Tests pass if I comment the following line.
        partial.make(basic_passing_short_fallout_test, fallout = "short"),
    )
```

**Comment by tetromino** [comment]
`partial` cannot be used to circumvent rule validation logic and set non-existent rule attributes.

If you want to set a `fallout` attribute for a rule, you have to define it first and give it a type:

```
basic_passing_short_fallout_test = unittest.make(_basic_passing_short_fallout_test, attrs = {'fallout': attr.string()})
```

But if you call `unittest.make` without the `attrs` argument, the rule would only allow [common rule attributes](https://bazel.build/reference/be/common-definitions#common-attributes) (e.g. `tags` and `visibility`) and [test rule attributes](https://bazel.build/reference/be/common-definitions#common-attributes-tests) (e.g. `size` and `timeout`). In which case you would only be able to use `partial` to set some of those common attributes, for example:

```
partial.make(basic_passing_short_timeout_test, tags = ["foo"])
```
