### ISSUE TITLE
Feature request: provide a module extension for checking Bazel version

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel-skylib#384]
bazel-skylib already provides a set of API for checking the current Bazel version, those APIs are not directly usable in MODULE.bazel when Bzlmod is enabled. We should write a module extension to make them available and can be used by Bazel modules to assert Bazel versions.

See https://github.com/bazelbuild/bazel-skylib/blob/main/lib/versions.bzl

**Comment by fmeum** [comment]
If we provide a module extension for this, we could think about making it purely declarative, e.g.

```
bazel_version = use_extension("@bazel_tools//extensions:version.bzl", "bazel_version")
bazel_version.required(minimum = "5.3.0", incompatible = ["5.3.1"])
```

The advantage would be that we could conceivably parse out these declarations and use them to populate the module metadata. We can't do that if we give module extensions arbitrary access to the Bazel version.

**Comment by meteorcloudy** [comment]
After some thoughts and discussion with @Wyverald and @andyrinne12, providing a module extension for Bazel version check will actually have some conflicts with https://github.com/bazelbuild/bazel/issues/16143

Because after https://github.com/bazelbuild/bazel/issues/16143, module extensions are not resolved eagerly. One module extension will only be resolved when one of its generated repo gets used. But the module extension doing the Bazel version check doesn't generate any repo, so it won't be triggered at all. 

One way to work around this is by adding an attribute to the module extension definition API for declaring the module extension to be eagerly resolved. But then that still isn't good enough, because we still needs to download all Bazel modules that provide any used module extensions to check if each module extension should be eagerly resolved or not. But after https://github.com/bazelbuild/bazel/issues/16143, it's possible to avoid downloading a Bazel module if repos provided by the module extension aren't used at all.

@Wyverald also mentioned we can probably generate a tiny repo that provides a toolchain and register that toolchain, this will force the module extension to be resolved because toolchain resolution forces all dependency repos to be fetched. But it sounds a bit hacky.

The other way is to just implement our [original design](https://docs.google.com/document/d/1moQfNcEIttsk6vYanNKIy3ZuK53hQUFq1b1r0rmsYVg/edit#heading=h.vxty4pj7bwk8) that adds the `bazel_compatibility` attribute to the `module` directive.
Eg.
```
module(
    name = "foo",
    version = "1.2.0",
    bazel_compatibility = [">=4.0.0", "<6.0.0", "-5.3.0"],
)
``` 

@fmeum WDYT?

**Comment by fmeum** [comment]
I actually find both the toolchain hack and the `bazel_compatibility` parameter on `module` to be decent solutions. I believe it's more of a question of maintainability that should guide whether we want to extend the Bzlmod API or prefer to use the existing one in creative ways.

**Comment by meteorcloudy** [comment]
I think from the user's perspective, the `bazel_compatibility` is more clean and easier to use, so that is my currently preference.

If you and @Wyverald both agree, @SalmaSamy could probably work on this. (first we need to move this issue to the bazel repo)
