### ISSUE TITLE
Feature request: Make "out" parameter of "native_binary" optional

### ISSUE THREAD

**Issue by carlosgalvezp** [bazelbuild/bazel-skylib#399]
Hi,

We find ourselves duplicating a lot of code for no benefit when using `native_binary`:

```
native_binary(
  name = "foo",
  src = "path/to/foo",
  out = "path/to/foo",
)
```

Would it be possible to make the `out` parameter optional, and if not set it should be set to the same path as the `src`? 

Thanks!

**Comment by tpudlik** [comment]
`src` is actually not suitable as a default because it may be in a different package than the `native_binary` target (and that's not allowed for a rule output). But I think setting the default to `name` would work. I'll give that a try.
