### ISSUE TITLE
Flag --incompatible_config_setting_private_default_visibility will break Bazel skylib in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel-skylib#414]
Incompatible flag `--incompatible_config_setting_private_default_visibility` will be enabled by default in the next major release (Bazel 7.0), thus breaking Bazel skylib. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: https://github.com/bazelbuild/bazel/issues/12933.

Please check the following CI builds for build and test results:

- [Ubuntu 18.04, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-f8dd-4c15-b75e-4aa54a7c5c98)
- [MacOS, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-f8d8-429a-8b3f-d707c43df045)
- [Ubuntu 16.04, OpenJDK 8](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-f8d5-4ac9-b6fa-4fab8c5ab305)
- [Ubuntu 18.04, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-f8d2-4138-999e-d9759fe9b2eb),
- [Windows, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-f8da-4542-8815-5b221b7a8091)
- [MacOS, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-f8cd-4a0f-8673-52e96b27fc57)
- [Ubuntu 16.04, OpenJDK 8](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-f8ca-423a-abb2-5ea808c9855b)
- [Ubuntu 18.04, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-f8c7-4cdc-b44b-64b794da4520)
- [Windows, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a207-f8cf-4e64-9334-8b430df54aa2)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by sgowroji** [comment]
Hi @bazel-skylib Team, Could you please look in to this issue.Thanks!

**Comment by tetromino** [comment]
The error is coming from an old `rules_pkg` dep - we need to bump it to 0.8 or newer.

**Comment by aiuto** [comment]
Can you point me at a reproduction for the failure. I can fix in rules_pkg.

**Comment by tetromino** [comment]
@aiuto - see https://buildkite.com/bazel/bazel-skylib/builds/2725

I suspect something about python toolchains changed in Bazel at HEAD
