### ISSUE TITLE
Brings in very old version of rules_cc: Eliminate or update?

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/bazel-skylib#475]
Hi wonderful Bazelers,

I was debugging something else and noticed that skylib brings in a very old version of rules_cc, breaking some things.

My understanding is that the dependency could probably be eliminated, since the cc rules used are built-in anyway--but failing that perhaps it would be worth an update?

Lmk what you think. Happy to help (though it might just be fastest to make the change, once you decide which makes more sense).

Thanks so much for all you do!
Chris
(ex-Googler)

**Comment by keith** [comment]
looks to me like it's only used for the imports, which is still not required. If it were me I would break that connection until it's required. Updating also seems harmless though

**Comment by cpsauer** [comment]
Sounds like we're on the same page. Thanks, as always, for being great Keith. Posted #476 doing just that, if you can merge.
