### ISSUE TITLE
How does unittest support attributes on the tests?

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/bazel-skylib#98]
[`unittest.make()`](https://github.com/bazelbuild/bazel-skylib/blob/master/lib/unittest.bzl#L62) is documented at taking an optional `attrs` that will be used from then `rule` is created for the test.

[`unittest.suite()`](https://github.com/bazelbuild/bazel-skylib/blob/master/lib/unittest.bzl#L118) is documented to create the rules from the list given to it, but in doing so, [only passes the `name` when creating the rules](https://github.com/bazelbuild/bazel-skylib/blob/master/lib/unittest.bzl#L163-L166).

How does one set the attributes for the testing rules created?

**Comment by dws-uber** [comment]
I had a need for this myself, and came up with a possible solution in https://github.com/bazelbuild/bazel-skylib/pull/276
